Docker
guoger/stupid pull request #69
Opened 2020-09-06 13:08 UTC by SamYuan1990

2020-09-06 13:48 UTC, guoger requested changes

2020-09-06 13:48 UTC, guoger commented on Dockerfile
> +FROM golang:1.14
let compile in `golang:1.14` and run in another image with smaller footprint, i.e. alpine, if possible at all

2020-09-15 13:26 UTC, guoger requested changes
generally looks good to me. but i think we don't need docker build in CI, and we probably should enable CD at some point

2020-09-15 13:26 UTC, guoger commented on test/integration-test.sh
> +# docker run
if we don't need them, pls kill these lines. otherwise, pls comment on why we need to keep them

2020-09-15 13:26 UTC, guoger commented on test/integration-test.sh
> +#go build ./cmd/stupid
if we don't need them, pls kill these lines. otherwise, pls comment on why we need to keep them

2020-09-15 13:26 UTC, guoger commented on azure-pipelines.yml
> +  - job:
why do we need a dockerbuild job in CI? it should be part of CD, no?

2020-09-15 13:26 UTC, guoger commented on azure-pipelines.yml
> +    displayName: build # docker build
what does `# docker build` indicate here?

2020-09-15 13:26 UTC, guoger commented on azure-pipelines.yml
> +          arguments: '-v ./... -cover'
why do we need `-cover` here? it's not reported to anywhere, right?

2020-09-15 13:26 UTC, guoger commented on test/integration-test.sh
> +docker run  -e STUPID_LOGLEVEL=debug --network host -v $PWD:/tmp stupid stupid $CONFIG_FILE 500
`/tmp` is not really meant to hold configs. you could just mount to `/config`

2020-09-20 11:18 UTC, SamYuan1990 commented
@guoger , updated "azp" logic below:

So far, use only for docker build. Ref pic below, copy from 
https://docs.microsoft.com/zh-cn/azure/devops/pipelines/migrate/from-travis?view=azure-devops

The azp run unit test and docker, then running for integration test.
Either ut fails or docker build fails will stop the pipeline.

![image](https://user-images.githubusercontent.com/7820992/93710012-aa972900-fb75-11ea-903d-9dca0af3cf87.png)

2020-09-23 14:01 UTC, guoger approved these changes

2020-09-23 14:01 UTC, merged